modLoader="javafml" #mandatory
loaderVersion="[45,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="nonetherportal" #mandatory
version="${file.jarVersion}" #mandatory
displayName="No Nether Portal!" #mandatory
authors="ZigTheHedge" #optional
description='''
This one just disables the Nether Portal ignition!
'''
[[dependencies.nonetherportal]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[45,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.nonetherportal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"
